apiVersion: v1
kind: Service
metadata:
  name: executionmanager-service
spec:
  type: NodePort
  selector:
    app: executionmanager
  ports:
    - targetPort: 54321
      port: 80
      nodePort: 30321